### ISSUE TITLE
linux installation issue with miniconda3 

### ISSUE THREAD

**Issue by joergbrech** [DLR-SC/cpacs2to3#9]
On Ubuntu `conda create -n cpacs2to3 python=3.5 cpacs2to3 -c dlr-sc` does not work properly: Running `cpacs2to3` gives the following error:

```
Traceback (most recent call last):
  File "/home/jan/tools/miniconda3/envs/cpacs2to3/bin/cpacs2to3", line 6, in <module>
    from cpacs2to3.cpacs_converter import main
  File "/home/jan/tools/miniconda3/envs/cpacs2to3/lib/python3.5/site-packages/cpacs2to3-0.2-py3.5.egg/cpacs2to3/cpacs_converter.py", line 27, in <module>
ImportError: No module named 'tixi'
```

Apparently tixi gets installed into the wrong directory (python3.6 rather than python3.5):

```
(cpacs2to3) jan@jan-notebook:~/tools/miniconda3/envs/cpacs2to3/lib$ find -name tixi
./python3.6/site-packages/tixi
./tixi
```

**Comment by joergbrech** [comment]
This is a tixi issue more than it is a cpacs2to3 issue. I just moved this here: https://github.com/DLR-SC/tixi/issues/116
